package com.alterego.lifesumtest;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LIFESUM_ITEM.
 */
public class LifesumItem {

    private Long id;
    private Integer categoryid;
    private Double fiber;
    private String headimage;
    private Double pcsingram;
    private String brand;
    private Double unsaturatedfat;
    private Double fat;
    private Integer servingcategory;
    private Integer typeofmeasurement;
    private Double protein;
    private Integer defaultserving;
    private Double mlingram;
    private Double saturatedfat;
    private String category;
    private Boolean verified;
    private String title;
    private String pcstext;
    private Double sodium;
    private Double carbohydrates;
    private Integer showonlysametype;
    private Integer calories;
    private Integer serving_version;
    private Double sugar;
    private Integer measurementid;
    private Double cholesterol;
    private Double gramsperserving;
    private Integer showmeasurement;
    private Double potassium;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LifesumItem() {
    }

    public LifesumItem(Long id) {
        this.id = id;
    }

    public LifesumItem(Long id, Integer categoryid, Double fiber, String headimage, Double pcsingram, String brand, Double unsaturatedfat, Double fat, Integer servingcategory, Integer typeofmeasurement, Double protein, Integer defaultserving, Double mlingram, Double saturatedfat, String category, Boolean verified, String title, String pcstext, Double sodium, Double carbohydrates, Integer showonlysametype, Integer calories, Integer serving_version, Double sugar, Integer measurementid, Double cholesterol, Double gramsperserving, Integer showmeasurement, Double potassium) {
        this.id = id;
        this.categoryid = categoryid;
        this.fiber = fiber;
        this.headimage = headimage;
        this.pcsingram = pcsingram;
        this.brand = brand;
        this.unsaturatedfat = unsaturatedfat;
        this.fat = fat;
        this.servingcategory = servingcategory;
        this.typeofmeasurement = typeofmeasurement;
        this.protein = protein;
        this.defaultserving = defaultserving;
        this.mlingram = mlingram;
        this.saturatedfat = saturatedfat;
        this.category = category;
        this.verified = verified;
        this.title = title;
        this.pcstext = pcstext;
        this.sodium = sodium;
        this.carbohydrates = carbohydrates;
        this.showonlysametype = showonlysametype;
        this.calories = calories;
        this.serving_version = serving_version;
        this.sugar = sugar;
        this.measurementid = measurementid;
        this.cholesterol = cholesterol;
        this.gramsperserving = gramsperserving;
        this.showmeasurement = showmeasurement;
        this.potassium = potassium;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCategoryid() {
        return categoryid;
    }

    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }

    public Double getFiber() {
        return fiber;
    }

    public void setFiber(Double fiber) {
        this.fiber = fiber;
    }

    public String getHeadimage() {
        return headimage;
    }

    public void setHeadimage(String headimage) {
        this.headimage = headimage;
    }

    public Double getPcsingram() {
        return pcsingram;
    }

    public void setPcsingram(Double pcsingram) {
        this.pcsingram = pcsingram;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public Double getUnsaturatedfat() {
        return unsaturatedfat;
    }

    public void setUnsaturatedfat(Double unsaturatedfat) {
        this.unsaturatedfat = unsaturatedfat;
    }

    public Double getFat() {
        return fat;
    }

    public void setFat(Double fat) {
        this.fat = fat;
    }

    public Integer getServingcategory() {
        return servingcategory;
    }

    public void setServingcategory(Integer servingcategory) {
        this.servingcategory = servingcategory;
    }

    public Integer getTypeofmeasurement() {
        return typeofmeasurement;
    }

    public void setTypeofmeasurement(Integer typeofmeasurement) {
        this.typeofmeasurement = typeofmeasurement;
    }

    public Double getProtein() {
        return protein;
    }

    public void setProtein(Double protein) {
        this.protein = protein;
    }

    public Integer getDefaultserving() {
        return defaultserving;
    }

    public void setDefaultserving(Integer defaultserving) {
        this.defaultserving = defaultserving;
    }

    public Double getMlingram() {
        return mlingram;
    }

    public void setMlingram(Double mlingram) {
        this.mlingram = mlingram;
    }

    public Double getSaturatedfat() {
        return saturatedfat;
    }

    public void setSaturatedfat(Double saturatedfat) {
        this.saturatedfat = saturatedfat;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Boolean getVerified() {
        return verified;
    }

    public void setVerified(Boolean verified) {
        this.verified = verified;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getPcstext() {
        return pcstext;
    }

    public void setPcstext(String pcstext) {
        this.pcstext = pcstext;
    }

    public Double getSodium() {
        return sodium;
    }

    public void setSodium(Double sodium) {
        this.sodium = sodium;
    }

    public Double getCarbohydrates() {
        return carbohydrates;
    }

    public void setCarbohydrates(Double carbohydrates) {
        this.carbohydrates = carbohydrates;
    }

    public Integer getShowonlysametype() {
        return showonlysametype;
    }

    public void setShowonlysametype(Integer showonlysametype) {
        this.showonlysametype = showonlysametype;
    }

    public Integer getCalories() {
        return calories;
    }

    public void setCalories(Integer calories) {
        this.calories = calories;
    }

    public Integer getServing_version() {
        return serving_version;
    }

    public void setServing_version(Integer serving_version) {
        this.serving_version = serving_version;
    }

    public Double getSugar() {
        return sugar;
    }

    public void setSugar(Double sugar) {
        this.sugar = sugar;
    }

    public Integer getMeasurementid() {
        return measurementid;
    }

    public void setMeasurementid(Integer measurementid) {
        this.measurementid = measurementid;
    }

    public Double getCholesterol() {
        return cholesterol;
    }

    public void setCholesterol(Double cholesterol) {
        this.cholesterol = cholesterol;
    }

    public Double getGramsperserving() {
        return gramsperserving;
    }

    public void setGramsperserving(Double gramsperserving) {
        this.gramsperserving = gramsperserving;
    }

    public Integer getShowmeasurement() {
        return showmeasurement;
    }

    public void setShowmeasurement(Integer showmeasurement) {
        this.showmeasurement = showmeasurement;
    }

    public Double getPotassium() {
        return potassium;
    }

    public void setPotassium(Double potassium) {
        this.potassium = potassium;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
